# Generated by Django 6.0.1 on 2026-01-19 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cartitem_is_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cleared',
            field=models.BooleanField(default=False),
        ),
    ]
