# Generated by Django 6.0.1 on 2026-01-19 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_order_cleared'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'pending'), ('Cooking', 'cooking'), ('Ready', 'ready'), ('Delivered', 'delivered')], default='Pending', max_length=20),
        ),
    ]
