# Generated by Django 6.0.1 on 2026-01-20 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_order_menu_item_cartitem_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.CharField(choices=[('Availlable', 'availlable'), ('Cancelled', 'cancelled'), ('Delivered', 'delivered')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled', models.BooleanField(default=False)),
            ],
        ),
    ]
