# Generated by Django 6.0.1 on 2026-01-20 10:51

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='booked_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table',
            name='booked_time',
            field=models.TimeField(auto_now_add=True, default=datetime.datetime(2026, 1, 20, 10, 51, 56, 876859, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table',
            name='booker_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='number_of_guests',
            field=models.IntegerField(default=2),
        ),
    ]
