# Generated by Django 6.0.1 on 2026-01-20 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_table_booked_date_table_booked_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='status',
            field=models.CharField(choices=[('Availlable', 'availlable'), ('Cancelled', 'cancelled'), ('Delivered', 'delivered')], default='Availlable', max_length=20),
        ),
    ]
